// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID           int    `json:"id"`
	PostID       int    `json:"postId"`
	ParentCommID *int   `json:"parentCommId,omitempty"`
	Text         string `json:"text"`
	AuthorID     int    `json:"authorId"`
}

type Mutation struct {
}

type NewPost struct {
	Title             string `json:"title"`
	Text              string `json:"text"`
	AuthorID          int    `json:"authorId"`
	IsCommentsUnabled bool   `json:"IsCommentsUnabled"`
}

type Post struct {
	ID                int    `json:"id"`
	Title             string `json:"title"`
	Text              string `json:"text"`
	AuthorID          int    `json:"authorId"`
	IsCommentsUnabled bool   `json:"IsCommentsUnabled"`
}

type Query struct {
}

type ResponseStatus struct {
	Text string `json:"text"`
}

type SwitchCommsType struct {
	PostID   int `json:"postId"`
	AuthorID int `json:"authorId"`
}

type User struct {
	ID    int    `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
