// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPost struct {
	Title             string `json:"title"`
	Text              string `json:"text"`
	AuthorID          int    `json:"authorId"`
	IsCommentsUnabled bool   `json:"IsCommentsUnabled"`
}

type Post struct {
	ID                int    `json:"id"`
	Title             string `json:"title"`
	Text              string `json:"text"`
	AuthorID          int    `json:"authorId"`
	IsCommentsUnabled bool   `json:"IsCommentsUnabled"`
}

type Query struct {
}

type User struct {
	ID    int    `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
